In [141]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [142]:
dataset=pd.read_csv('Data3.csv')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:, -1].values


In [143]:
print(x)

[['France' 44.0 72000.0 nan]
 ['Spain' 27.0 48000.0 32.0]
 ['Germany' 30.0 54000.0 23.0]
 ['Spain' 38.0 61000.0 33.0]
 ['Germany' 40.0 nan 43.0]
 ['France' 35.0 58000.0 32.0]
 ['Spain' nan 52000.0 35.0]
 ['France' 48.0 nan 38.0]
 ['Germany' 50.0 83000.0 32.0]
 ['France' 37.0 67000.0 32.0]]


In [144]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [145]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:4])
x[:, 1:4]=imputer.transform(x[:, 1:4])

In [146]:
print(x)

[['France' 44.0 72000.0 33.333333333333336]
 ['Spain' 27.0 48000.0 32.0]
 ['Germany' 30.0 54000.0 23.0]
 ['Spain' 38.0 61000.0 33.0]
 ['Germany' 40.0 61875.0 43.0]
 ['France' 35.0 58000.0 32.0]
 ['Spain' 38.77777777777778 52000.0 35.0]
 ['France' 48.0 61875.0 38.0]
 ['Germany' 50.0 83000.0 32.0]
 ['France' 37.0 67000.0 32.0]]


In [147]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [148]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0 33.333333333333336]
 [0.0 0.0 1.0 27.0 48000.0 32.0]
 [0.0 1.0 0.0 30.0 54000.0 23.0]
 [0.0 0.0 1.0 38.0 61000.0 33.0]
 [0.0 1.0 0.0 40.0 61875.0 43.0]
 [1.0 0.0 0.0 35.0 58000.0 32.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0 35.0]
 [1.0 0.0 0.0 48.0 61875.0 38.0]
 [0.0 1.0 0.0 50.0 83000.0 32.0]
 [1.0 0.0 0.0 37.0 67000.0 32.0]]


In [149]:
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()
y=le.fit_transform(y)

In [150]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [151]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [152]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0 35.0]
 [0.0 1.0 0.0 40.0 61875.0 43.0]
 [1.0 0.0 0.0 44.0 72000.0 33.333333333333336]
 [0.0 0.0 1.0 38.0 61000.0 33.0]
 [0.0 0.0 1.0 27.0 48000.0 32.0]
 [1.0 0.0 0.0 48.0 61875.0 38.0]
 [0.0 1.0 0.0 50.0 83000.0 32.0]
 [1.0 0.0 0.0 35.0 58000.0 32.0]]


In [153]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0 23.0]
 [1.0 0.0 0.0 37.0 67000.0 32.0]]


In [154]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [155]:
print(y_test)

[0 1]


In [156]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 4:] = sc.fit_transform(x_train[:, 4:])
x_test[:, 4:]= sc.transform(x_test[:, 4:])

In [157]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 -0.9892435857079551 0.05711768428217229]
 [0.0 1.0 0.0 40.0 -0.033277307164487784 2.250436760717638]
 [1.0 0.0 0.0 44.0 0.9468906493167888 -0.3998237899752157]
 [0.0 0.0 1.0 38.0 -0.11798317994682034 -0.49121208482669415]
 [0.0 0.0 1.0 27.0 -1.3764704327129038 -0.7653769693811273]
 [1.0 0.0 0.0 48.0 -0.033277307164487784 0.8796123379454719]
 [0.0 1.0 0.0 50.0 2.011764478580398 -0.7653769693811273]
 [1.0 0.0 0.0 35.0 -0.4084033152005319 -0.7653769693811273]]
